modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL = "https://github.com/Alan19/Astral/issues"
license = "MIT"

[[mods]]
modId = "astral"
version = "${file.jarVersion}"
displayName = "Astral"
displayURL = "https://github.com/Alan19/Astral"
credits = "Thanks to Divineaspect for designing and planning the mod and Lance5057 and Snurly for some of the textures!"
authors = "Alan199921"
description = '''A practice of the arts of psychic projection and inversion, the exploration of the psychic world hidden around us, and the development of the inner worlds of the mind of the practitioner.'''

[[dependencies.astral]]
modId = "patchouli"
mandatory = true
versionRange = "[1.16.2-47,)"
side = "BOTH"

[[dependencies.astral]]
modId = "botania"
mandatory = false
versionRange = "[r1.16.3-409,)"
side = "BOTH"