modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/Alan19/Astral/issues"
[[mods]]
modId="astral"
version="${file.jarVersion}"
displayName="Astral"
updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/Alan19/Astral" #optional
logoFile="examplemod.png" #optional
credits="Thanks to Divineaspect for designing and planning the mod and Lance5057 for some of the textures!" #optional
authors="Alan199921"
description='''A mod about astral projection and introspection.'''